# Uncomment the next line to define a global platform for your project
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :macos, '11'

target 'MacOS_App_Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Sparkle'


  # Pods for MacOS_App_Test

end
